#
# Copyright (C) 2012 Sony Mobile Communications AB.
#


#[SA77] ==> CCI KLog, added by Jimmy@CCI
obj-$(CONFIG_CCI_KLOG)	+=	klog/
#[SA77] <== CCI KLog, added by Jimmy@CCI

obj-$(CONFIG_CCI_STUFF)	+=	cci_stuff/

# S:LE
obj-$(CONFIG_CCI_KERNEL_INFO)	+=	cci_kernel_info/
# E:LE

obj-$(CONFIG_CCI_SOMC_XSSM)     +=      somc_xssm/
obj-$(CONFIG_CCI_SOMC_SW_INFO)	+=	somc_sw/
obj-$(CONFIG_CCI_POWERMONITOR)  +=      cci_powermonitor/
